package com.jd.secondproject.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RentBrokerStaffExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rent_broker_staff
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rent_broker_staff
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rent_broker_staff
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rent_broker_staff
     *
     * @mbggenerated
     */
    public RentBrokerStaffExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rent_broker_staff
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rent_broker_staff
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rent_broker_staff
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rent_broker_staff
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rent_broker_staff
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rent_broker_staff
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rent_broker_staff
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rent_broker_staff
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rent_broker_staff
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rent_broker_staff
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rent_broker_staff
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdIsNull() {
            addCriterion("broker_staff_id is null");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdIsNotNull() {
            addCriterion("broker_staff_id is not null");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdEqualTo(Long value) {
            addCriterion("broker_staff_id =", value, "brokerStaffId");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdNotEqualTo(Long value) {
            addCriterion("broker_staff_id <>", value, "brokerStaffId");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdGreaterThan(Long value) {
            addCriterion("broker_staff_id >", value, "brokerStaffId");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdGreaterThanOrEqualTo(Long value) {
            addCriterion("broker_staff_id >=", value, "brokerStaffId");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdLessThan(Long value) {
            addCriterion("broker_staff_id <", value, "brokerStaffId");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdLessThanOrEqualTo(Long value) {
            addCriterion("broker_staff_id <=", value, "brokerStaffId");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdIn(List<Long> values) {
            addCriterion("broker_staff_id in", values, "brokerStaffId");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdNotIn(List<Long> values) {
            addCriterion("broker_staff_id not in", values, "brokerStaffId");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdBetween(Long value1, Long value2) {
            addCriterion("broker_staff_id between", value1, value2, "brokerStaffId");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdNotBetween(Long value1, Long value2) {
            addCriterion("broker_staff_id not between", value1, value2, "brokerStaffId");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffNameIsNull() {
            addCriterion("broker_staff_name is null");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffNameIsNotNull() {
            addCriterion("broker_staff_name is not null");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffNameEqualTo(String value) {
            addCriterion("broker_staff_name =", value, "brokerStaffName");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffNameNotEqualTo(String value) {
            addCriterion("broker_staff_name <>", value, "brokerStaffName");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffNameGreaterThan(String value) {
            addCriterion("broker_staff_name >", value, "brokerStaffName");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffNameGreaterThanOrEqualTo(String value) {
            addCriterion("broker_staff_name >=", value, "brokerStaffName");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffNameLessThan(String value) {
            addCriterion("broker_staff_name <", value, "brokerStaffName");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffNameLessThanOrEqualTo(String value) {
            addCriterion("broker_staff_name <=", value, "brokerStaffName");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffNameLike(String value) {
            addCriterion("broker_staff_name like", value, "brokerStaffName");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffNameNotLike(String value) {
            addCriterion("broker_staff_name not like", value, "brokerStaffName");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffNameIn(List<String> values) {
            addCriterion("broker_staff_name in", values, "brokerStaffName");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffNameNotIn(List<String> values) {
            addCriterion("broker_staff_name not in", values, "brokerStaffName");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffNameBetween(String value1, String value2) {
            addCriterion("broker_staff_name between", value1, value2, "brokerStaffName");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffNameNotBetween(String value1, String value2) {
            addCriterion("broker_staff_name not between", value1, value2, "brokerStaffName");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffPhoneIsNull() {
            addCriterion("broker_staff_phone is null");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffPhoneIsNotNull() {
            addCriterion("broker_staff_phone is not null");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffPhoneEqualTo(String value) {
            addCriterion("broker_staff_phone =", value, "brokerStaffPhone");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffPhoneNotEqualTo(String value) {
            addCriterion("broker_staff_phone <>", value, "brokerStaffPhone");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffPhoneGreaterThan(String value) {
            addCriterion("broker_staff_phone >", value, "brokerStaffPhone");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("broker_staff_phone >=", value, "brokerStaffPhone");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffPhoneLessThan(String value) {
            addCriterion("broker_staff_phone <", value, "brokerStaffPhone");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffPhoneLessThanOrEqualTo(String value) {
            addCriterion("broker_staff_phone <=", value, "brokerStaffPhone");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffPhoneLike(String value) {
            addCriterion("broker_staff_phone like", value, "brokerStaffPhone");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffPhoneNotLike(String value) {
            addCriterion("broker_staff_phone not like", value, "brokerStaffPhone");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffPhoneIn(List<String> values) {
            addCriterion("broker_staff_phone in", values, "brokerStaffPhone");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffPhoneNotIn(List<String> values) {
            addCriterion("broker_staff_phone not in", values, "brokerStaffPhone");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffPhoneBetween(String value1, String value2) {
            addCriterion("broker_staff_phone between", value1, value2, "brokerStaffPhone");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffPhoneNotBetween(String value1, String value2) {
            addCriterion("broker_staff_phone not between", value1, value2, "brokerStaffPhone");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffGenderIsNull() {
            addCriterion("broker_staff_gender is null");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffGenderIsNotNull() {
            addCriterion("broker_staff_gender is not null");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffGenderEqualTo(Integer value) {
            addCriterion("broker_staff_gender =", value, "brokerStaffGender");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffGenderNotEqualTo(Integer value) {
            addCriterion("broker_staff_gender <>", value, "brokerStaffGender");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffGenderGreaterThan(Integer value) {
            addCriterion("broker_staff_gender >", value, "brokerStaffGender");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffGenderGreaterThanOrEqualTo(Integer value) {
            addCriterion("broker_staff_gender >=", value, "brokerStaffGender");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffGenderLessThan(Integer value) {
            addCriterion("broker_staff_gender <", value, "brokerStaffGender");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffGenderLessThanOrEqualTo(Integer value) {
            addCriterion("broker_staff_gender <=", value, "brokerStaffGender");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffGenderIn(List<Integer> values) {
            addCriterion("broker_staff_gender in", values, "brokerStaffGender");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffGenderNotIn(List<Integer> values) {
            addCriterion("broker_staff_gender not in", values, "brokerStaffGender");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffGenderBetween(Integer value1, Integer value2) {
            addCriterion("broker_staff_gender between", value1, value2, "brokerStaffGender");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffGenderNotBetween(Integer value1, Integer value2) {
            addCriterion("broker_staff_gender not between", value1, value2, "brokerStaffGender");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardnumIsNull() {
            addCriterion("broker_staff_idcardnum is null");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardnumIsNotNull() {
            addCriterion("broker_staff_idcardnum is not null");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardnumEqualTo(String value) {
            addCriterion("broker_staff_idcardnum =", value, "brokerStaffIdcardnum");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardnumNotEqualTo(String value) {
            addCriterion("broker_staff_idcardnum <>", value, "brokerStaffIdcardnum");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardnumGreaterThan(String value) {
            addCriterion("broker_staff_idcardnum >", value, "brokerStaffIdcardnum");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardnumGreaterThanOrEqualTo(String value) {
            addCriterion("broker_staff_idcardnum >=", value, "brokerStaffIdcardnum");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardnumLessThan(String value) {
            addCriterion("broker_staff_idcardnum <", value, "brokerStaffIdcardnum");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardnumLessThanOrEqualTo(String value) {
            addCriterion("broker_staff_idcardnum <=", value, "brokerStaffIdcardnum");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardnumLike(String value) {
            addCriterion("broker_staff_idcardnum like", value, "brokerStaffIdcardnum");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardnumNotLike(String value) {
            addCriterion("broker_staff_idcardnum not like", value, "brokerStaffIdcardnum");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardnumIn(List<String> values) {
            addCriterion("broker_staff_idcardnum in", values, "brokerStaffIdcardnum");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardnumNotIn(List<String> values) {
            addCriterion("broker_staff_idcardnum not in", values, "brokerStaffIdcardnum");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardnumBetween(String value1, String value2) {
            addCriterion("broker_staff_idcardnum between", value1, value2, "brokerStaffIdcardnum");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardnumNotBetween(String value1, String value2) {
            addCriterion("broker_staff_idcardnum not between", value1, value2, "brokerStaffIdcardnum");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffImgIsNull() {
            addCriterion("broker_staff_img is null");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffImgIsNotNull() {
            addCriterion("broker_staff_img is not null");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffImgEqualTo(String value) {
            addCriterion("broker_staff_img =", value, "brokerStaffImg");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffImgNotEqualTo(String value) {
            addCriterion("broker_staff_img <>", value, "brokerStaffImg");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffImgGreaterThan(String value) {
            addCriterion("broker_staff_img >", value, "brokerStaffImg");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffImgGreaterThanOrEqualTo(String value) {
            addCriterion("broker_staff_img >=", value, "brokerStaffImg");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffImgLessThan(String value) {
            addCriterion("broker_staff_img <", value, "brokerStaffImg");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffImgLessThanOrEqualTo(String value) {
            addCriterion("broker_staff_img <=", value, "brokerStaffImg");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffImgLike(String value) {
            addCriterion("broker_staff_img like", value, "brokerStaffImg");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffImgNotLike(String value) {
            addCriterion("broker_staff_img not like", value, "brokerStaffImg");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffImgIn(List<String> values) {
            addCriterion("broker_staff_img in", values, "brokerStaffImg");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffImgNotIn(List<String> values) {
            addCriterion("broker_staff_img not in", values, "brokerStaffImg");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffImgBetween(String value1, String value2) {
            addCriterion("broker_staff_img between", value1, value2, "brokerStaffImg");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffImgNotBetween(String value1, String value2) {
            addCriterion("broker_staff_img not between", value1, value2, "brokerStaffImg");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardfrontIsNull() {
            addCriterion("broker_staff_idcardfront is null");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardfrontIsNotNull() {
            addCriterion("broker_staff_idcardfront is not null");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardfrontEqualTo(String value) {
            addCriterion("broker_staff_idcardfront =", value, "brokerStaffIdcardfront");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardfrontNotEqualTo(String value) {
            addCriterion("broker_staff_idcardfront <>", value, "brokerStaffIdcardfront");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardfrontGreaterThan(String value) {
            addCriterion("broker_staff_idcardfront >", value, "brokerStaffIdcardfront");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardfrontGreaterThanOrEqualTo(String value) {
            addCriterion("broker_staff_idcardfront >=", value, "brokerStaffIdcardfront");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardfrontLessThan(String value) {
            addCriterion("broker_staff_idcardfront <", value, "brokerStaffIdcardfront");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardfrontLessThanOrEqualTo(String value) {
            addCriterion("broker_staff_idcardfront <=", value, "brokerStaffIdcardfront");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardfrontLike(String value) {
            addCriterion("broker_staff_idcardfront like", value, "brokerStaffIdcardfront");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardfrontNotLike(String value) {
            addCriterion("broker_staff_idcardfront not like", value, "brokerStaffIdcardfront");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardfrontIn(List<String> values) {
            addCriterion("broker_staff_idcardfront in", values, "brokerStaffIdcardfront");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardfrontNotIn(List<String> values) {
            addCriterion("broker_staff_idcardfront not in", values, "brokerStaffIdcardfront");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardfrontBetween(String value1, String value2) {
            addCriterion("broker_staff_idcardfront between", value1, value2, "brokerStaffIdcardfront");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardfrontNotBetween(String value1, String value2) {
            addCriterion("broker_staff_idcardfront not between", value1, value2, "brokerStaffIdcardfront");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardbackIsNull() {
            addCriterion("broker_staff_idcardback is null");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardbackIsNotNull() {
            addCriterion("broker_staff_idcardback is not null");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardbackEqualTo(String value) {
            addCriterion("broker_staff_idcardback =", value, "brokerStaffIdcardback");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardbackNotEqualTo(String value) {
            addCriterion("broker_staff_idcardback <>", value, "brokerStaffIdcardback");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardbackGreaterThan(String value) {
            addCriterion("broker_staff_idcardback >", value, "brokerStaffIdcardback");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardbackGreaterThanOrEqualTo(String value) {
            addCriterion("broker_staff_idcardback >=", value, "brokerStaffIdcardback");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardbackLessThan(String value) {
            addCriterion("broker_staff_idcardback <", value, "brokerStaffIdcardback");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardbackLessThanOrEqualTo(String value) {
            addCriterion("broker_staff_idcardback <=", value, "brokerStaffIdcardback");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardbackLike(String value) {
            addCriterion("broker_staff_idcardback like", value, "brokerStaffIdcardback");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardbackNotLike(String value) {
            addCriterion("broker_staff_idcardback not like", value, "brokerStaffIdcardback");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardbackIn(List<String> values) {
            addCriterion("broker_staff_idcardback in", values, "brokerStaffIdcardback");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardbackNotIn(List<String> values) {
            addCriterion("broker_staff_idcardback not in", values, "brokerStaffIdcardback");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardbackBetween(String value1, String value2) {
            addCriterion("broker_staff_idcardback between", value1, value2, "brokerStaffIdcardback");
            return (Criteria) this;
        }

        public Criteria andBrokerStaffIdcardbackNotBetween(String value1, String value2) {
            addCriterion("broker_staff_idcardback not between", value1, value2, "brokerStaffIdcardback");
            return (Criteria) this;
        }

        public Criteria andBrokerNameIsNull() {
            addCriterion("broker_name is null");
            return (Criteria) this;
        }

        public Criteria andBrokerNameIsNotNull() {
            addCriterion("broker_name is not null");
            return (Criteria) this;
        }

        public Criteria andBrokerNameEqualTo(String value) {
            addCriterion("broker_name =", value, "brokerName");
            return (Criteria) this;
        }

        public Criteria andBrokerNameNotEqualTo(String value) {
            addCriterion("broker_name <>", value, "brokerName");
            return (Criteria) this;
        }

        public Criteria andBrokerNameGreaterThan(String value) {
            addCriterion("broker_name >", value, "brokerName");
            return (Criteria) this;
        }

        public Criteria andBrokerNameGreaterThanOrEqualTo(String value) {
            addCriterion("broker_name >=", value, "brokerName");
            return (Criteria) this;
        }

        public Criteria andBrokerNameLessThan(String value) {
            addCriterion("broker_name <", value, "brokerName");
            return (Criteria) this;
        }

        public Criteria andBrokerNameLessThanOrEqualTo(String value) {
            addCriterion("broker_name <=", value, "brokerName");
            return (Criteria) this;
        }

        public Criteria andBrokerNameLike(String value) {
            addCriterion("broker_name like", value, "brokerName");
            return (Criteria) this;
        }

        public Criteria andBrokerNameNotLike(String value) {
            addCriterion("broker_name not like", value, "brokerName");
            return (Criteria) this;
        }

        public Criteria andBrokerNameIn(List<String> values) {
            addCriterion("broker_name in", values, "brokerName");
            return (Criteria) this;
        }

        public Criteria andBrokerNameNotIn(List<String> values) {
            addCriterion("broker_name not in", values, "brokerName");
            return (Criteria) this;
        }

        public Criteria andBrokerNameBetween(String value1, String value2) {
            addCriterion("broker_name between", value1, value2, "brokerName");
            return (Criteria) this;
        }

        public Criteria andBrokerNameNotBetween(String value1, String value2) {
            addCriterion("broker_name not between", value1, value2, "brokerName");
            return (Criteria) this;
        }

        public Criteria andBrokerIdIsNull() {
            addCriterion("broker_id is null");
            return (Criteria) this;
        }

        public Criteria andBrokerIdIsNotNull() {
            addCriterion("broker_id is not null");
            return (Criteria) this;
        }

        public Criteria andBrokerIdEqualTo(Integer value) {
            addCriterion("broker_id =", value, "brokerId");
            return (Criteria) this;
        }

        public Criteria andBrokerIdNotEqualTo(Integer value) {
            addCriterion("broker_id <>", value, "brokerId");
            return (Criteria) this;
        }

        public Criteria andBrokerIdGreaterThan(Integer value) {
            addCriterion("broker_id >", value, "brokerId");
            return (Criteria) this;
        }

        public Criteria andBrokerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("broker_id >=", value, "brokerId");
            return (Criteria) this;
        }

        public Criteria andBrokerIdLessThan(Integer value) {
            addCriterion("broker_id <", value, "brokerId");
            return (Criteria) this;
        }

        public Criteria andBrokerIdLessThanOrEqualTo(Integer value) {
            addCriterion("broker_id <=", value, "brokerId");
            return (Criteria) this;
        }

        public Criteria andBrokerIdIn(List<Integer> values) {
            addCriterion("broker_id in", values, "brokerId");
            return (Criteria) this;
        }

        public Criteria andBrokerIdNotIn(List<Integer> values) {
            addCriterion("broker_id not in", values, "brokerId");
            return (Criteria) this;
        }

        public Criteria andBrokerIdBetween(Integer value1, Integer value2) {
            addCriterion("broker_id between", value1, value2, "brokerId");
            return (Criteria) this;
        }

        public Criteria andBrokerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("broker_id not between", value1, value2, "brokerId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andYnIsNull() {
            addCriterion("yn is null");
            return (Criteria) this;
        }

        public Criteria andYnIsNotNull() {
            addCriterion("yn is not null");
            return (Criteria) this;
        }

        public Criteria andYnEqualTo(Short value) {
            addCriterion("yn =", value, "yn");
            return (Criteria) this;
        }

        public Criteria andYnNotEqualTo(Short value) {
            addCriterion("yn <>", value, "yn");
            return (Criteria) this;
        }

        public Criteria andYnGreaterThan(Short value) {
            addCriterion("yn >", value, "yn");
            return (Criteria) this;
        }

        public Criteria andYnGreaterThanOrEqualTo(Short value) {
            addCriterion("yn >=", value, "yn");
            return (Criteria) this;
        }

        public Criteria andYnLessThan(Short value) {
            addCriterion("yn <", value, "yn");
            return (Criteria) this;
        }

        public Criteria andYnLessThanOrEqualTo(Short value) {
            addCriterion("yn <=", value, "yn");
            return (Criteria) this;
        }

        public Criteria andYnIn(List<Short> values) {
            addCriterion("yn in", values, "yn");
            return (Criteria) this;
        }

        public Criteria andYnNotIn(List<Short> values) {
            addCriterion("yn not in", values, "yn");
            return (Criteria) this;
        }

        public Criteria andYnBetween(Short value1, Short value2) {
            addCriterion("yn between", value1, value2, "yn");
            return (Criteria) this;
        }

        public Criteria andYnNotBetween(Short value1, Short value2) {
            addCriterion("yn not between", value1, value2, "yn");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rent_broker_staff
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rent_broker_staff
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}