package com.jd.secondproject.domain;

import java.util.Date;

public class RentBrokerStaff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_broker_staff.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_broker_staff.broker_staff_id
     *
     * @mbggenerated
     */
    private Long brokerStaffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_broker_staff.broker_staff_name
     *
     * @mbggenerated
     */
    private String brokerStaffName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_broker_staff.broker_staff_phone
     *
     * @mbggenerated
     */
    private String brokerStaffPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_broker_staff.broker_staff_gender
     *
     * @mbggenerated
     */
    private Integer brokerStaffGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_broker_staff.broker_staff_idcardnum
     *
     * @mbggenerated
     */
    private String brokerStaffIdcardnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_broker_staff.broker_staff_img
     *
     * @mbggenerated
     */
    private String brokerStaffImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_broker_staff.broker_staff_idcardfront
     *
     * @mbggenerated
     */
    private String brokerStaffIdcardfront;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_broker_staff.broker_staff_idcardback
     *
     * @mbggenerated
     */
    private String brokerStaffIdcardback;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_broker_staff.broker_name
     *
     * @mbggenerated
     */
    private String brokerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_broker_staff.broker_id
     *
     * @mbggenerated
     */
    private Integer brokerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_broker_staff.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_broker_staff.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_broker_staff.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_broker_staff.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rent_broker_staff.yn
     *
     * @mbggenerated
     */
    private Short yn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_broker_staff.id
     *
     * @return the value of rent_broker_staff.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_broker_staff.id
     *
     * @param id the value for rent_broker_staff.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_broker_staff.broker_staff_id
     *
     * @return the value of rent_broker_staff.broker_staff_id
     *
     * @mbggenerated
     */
    public Long getBrokerStaffId() {
        return brokerStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_broker_staff.broker_staff_id
     *
     * @param brokerStaffId the value for rent_broker_staff.broker_staff_id
     *
     * @mbggenerated
     */
    public void setBrokerStaffId(Long brokerStaffId) {
        this.brokerStaffId = brokerStaffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_broker_staff.broker_staff_name
     *
     * @return the value of rent_broker_staff.broker_staff_name
     *
     * @mbggenerated
     */
    public String getBrokerStaffName() {
        return brokerStaffName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_broker_staff.broker_staff_name
     *
     * @param brokerStaffName the value for rent_broker_staff.broker_staff_name
     *
     * @mbggenerated
     */
    public void setBrokerStaffName(String brokerStaffName) {
        this.brokerStaffName = brokerStaffName == null ? null : brokerStaffName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_broker_staff.broker_staff_phone
     *
     * @return the value of rent_broker_staff.broker_staff_phone
     *
     * @mbggenerated
     */
    public String getBrokerStaffPhone() {
        return brokerStaffPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_broker_staff.broker_staff_phone
     *
     * @param brokerStaffPhone the value for rent_broker_staff.broker_staff_phone
     *
     * @mbggenerated
     */
    public void setBrokerStaffPhone(String brokerStaffPhone) {
        this.brokerStaffPhone = brokerStaffPhone == null ? null : brokerStaffPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_broker_staff.broker_staff_gender
     *
     * @return the value of rent_broker_staff.broker_staff_gender
     *
     * @mbggenerated
     */
    public Integer getBrokerStaffGender() {
        return brokerStaffGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_broker_staff.broker_staff_gender
     *
     * @param brokerStaffGender the value for rent_broker_staff.broker_staff_gender
     *
     * @mbggenerated
     */
    public void setBrokerStaffGender(Integer brokerStaffGender) {
        this.brokerStaffGender = brokerStaffGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_broker_staff.broker_staff_idcardnum
     *
     * @return the value of rent_broker_staff.broker_staff_idcardnum
     *
     * @mbggenerated
     */
    public String getBrokerStaffIdcardnum() {
        return brokerStaffIdcardnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_broker_staff.broker_staff_idcardnum
     *
     * @param brokerStaffIdcardnum the value for rent_broker_staff.broker_staff_idcardnum
     *
     * @mbggenerated
     */
    public void setBrokerStaffIdcardnum(String brokerStaffIdcardnum) {
        this.brokerStaffIdcardnum = brokerStaffIdcardnum == null ? null : brokerStaffIdcardnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_broker_staff.broker_staff_img
     *
     * @return the value of rent_broker_staff.broker_staff_img
     *
     * @mbggenerated
     */
    public String getBrokerStaffImg() {
        return brokerStaffImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_broker_staff.broker_staff_img
     *
     * @param brokerStaffImg the value for rent_broker_staff.broker_staff_img
     *
     * @mbggenerated
     */
    public void setBrokerStaffImg(String brokerStaffImg) {
        this.brokerStaffImg = brokerStaffImg == null ? null : brokerStaffImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_broker_staff.broker_staff_idcardfront
     *
     * @return the value of rent_broker_staff.broker_staff_idcardfront
     *
     * @mbggenerated
     */
    public String getBrokerStaffIdcardfront() {
        return brokerStaffIdcardfront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_broker_staff.broker_staff_idcardfront
     *
     * @param brokerStaffIdcardfront the value for rent_broker_staff.broker_staff_idcardfront
     *
     * @mbggenerated
     */
    public void setBrokerStaffIdcardfront(String brokerStaffIdcardfront) {
        this.brokerStaffIdcardfront = brokerStaffIdcardfront == null ? null : brokerStaffIdcardfront.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_broker_staff.broker_staff_idcardback
     *
     * @return the value of rent_broker_staff.broker_staff_idcardback
     *
     * @mbggenerated
     */
    public String getBrokerStaffIdcardback() {
        return brokerStaffIdcardback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_broker_staff.broker_staff_idcardback
     *
     * @param brokerStaffIdcardback the value for rent_broker_staff.broker_staff_idcardback
     *
     * @mbggenerated
     */
    public void setBrokerStaffIdcardback(String brokerStaffIdcardback) {
        this.brokerStaffIdcardback = brokerStaffIdcardback == null ? null : brokerStaffIdcardback.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_broker_staff.broker_name
     *
     * @return the value of rent_broker_staff.broker_name
     *
     * @mbggenerated
     */
    public String getBrokerName() {
        return brokerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_broker_staff.broker_name
     *
     * @param brokerName the value for rent_broker_staff.broker_name
     *
     * @mbggenerated
     */
    public void setBrokerName(String brokerName) {
        this.brokerName = brokerName == null ? null : brokerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_broker_staff.broker_id
     *
     * @return the value of rent_broker_staff.broker_id
     *
     * @mbggenerated
     */
    public Integer getBrokerId() {
        return brokerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_broker_staff.broker_id
     *
     * @param brokerId the value for rent_broker_staff.broker_id
     *
     * @mbggenerated
     */
    public void setBrokerId(Integer brokerId) {
        this.brokerId = brokerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_broker_staff.create_time
     *
     * @return the value of rent_broker_staff.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_broker_staff.create_time
     *
     * @param createTime the value for rent_broker_staff.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_broker_staff.update_time
     *
     * @return the value of rent_broker_staff.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_broker_staff.update_time
     *
     * @param updateTime the value for rent_broker_staff.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_broker_staff.create_user
     *
     * @return the value of rent_broker_staff.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_broker_staff.create_user
     *
     * @param createUser the value for rent_broker_staff.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_broker_staff.update_user
     *
     * @return the value of rent_broker_staff.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_broker_staff.update_user
     *
     * @param updateUser the value for rent_broker_staff.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rent_broker_staff.yn
     *
     * @return the value of rent_broker_staff.yn
     *
     * @mbggenerated
     */
    public Short getYn() {
        return yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rent_broker_staff.yn
     *
     * @param yn the value for rent_broker_staff.yn
     *
     * @mbggenerated
     */
    public void setYn(Short yn) {
        this.yn = yn;
    }
}